name: Setup Python
description: Setup Python

inputs:
  python-version:
    description: Python version
    required: false
    default: "3.13"
  args:
    description: Additional arguments to pass to the install command
    required: false

runs:
  using: "composite"
  steps:
    - name: Install poetry
      run: pipx install poetry
      shell: bash

    - uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}
        cache: "poetry"

    - run: poetry install --all-extras
      shell: bash
